import { Button } from '@/components/ui/button';
import { Head, Link } from '@inertiajs/react';
import { ArrowLeft, Building2, CalendarDays, Eye, MapPin, Tag } from 'lucide-react';
import { useEffect, useState } from 'react';
import EditVacancy from './Edit';
import { Vacancy,Category,Company } from './Index';
import Categoury from '../categoure/Index';
export default function ShowVacancy({vacancy,categories,companies}: { vacancy:Vacancy,companies:Company[],categories:Category[]}) {
    const [selectvacanc,setselectvacanc]=useState<Vacancy|null>(null)
    console.log(vacancy);
    
    return <>
    <Head title={vacancy.Title} /><main className="min-h-screen bg-[#f7f8fa] px-4 py-8 text-slate-900 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl"><Link href="/Jopvacancies" className="inline-flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-[#173c3a]"><ArrowLeft className="size-4" />Back to vacancies</Link><header className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-[0_12px_40px_rgba(15,23,42,0.04)] sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#d86b3d]">Job vacancy</p><h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">{vacancy.Title}</h1><div className="mt-4 flex flex-wrap gap-4 text-sm text-slate-500"><span className="inline-flex items-center gap-2"><Building2 className="size-4" />{vacancy.company?.name || 'Company unavailable'}</span><span className="inline-flex items-center gap-2"><MapPin className="size-4" />{vacancy.Location}</span><span className="inline-flex items-center gap-2"><Tag className="size-4" />{vacancy.categoury?.Name || 'Uncategorized'}</span></div></div><Button onClick={()=>{setselectvacanc(vacancy)}} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 hover:text-[#173c3a]"> Update</Button></div></header><div className="mt-6 grid gap-6 lg:grid-cols-[1.4fr_0.6fr]"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><h2 className="text-xl font-semibold">Description</h2><p className="mt-4 whitespace-pre-line text-sm leading-7 text-slate-600">{vacancy.Description}</p><h2 className="mt-8 text-xl font-semibold">Required skills</h2><p className="mt-4 whitespace-pre-line text-sm leading-7 text-slate-600">{vacancy.Requiredskills}</p></section><aside className="space-y-6"><section className="rounded-3xl bg-[#173c3a] p-6 text-white shadow-lg"><p className="text-xs uppercase tracking-[0.18em] text-[#f2b28f]">Compensation</p><p className="mt-3 text-3xl font-bold">${Number(vacancy.Salary).toLocaleString()}</p><p className="mt-1 text-sm text-white/65">{vacancy.Type === '1' ? 'Full time' : 'Part time'}</p></section><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#d86b3d]">Activity</p><div className="mt-5 space-y-4 text-sm"><div className="flex items-center gap-3"><Eye className="size-4 text-slate-400" /><span className="text-slate-600">{vacancy.Viewcount} views</span></div><div className="flex items-center gap-3"><CalendarDays className="size-4 text-slate-400" /><span className="text-slate-600">Posted {new Date(vacancy.created_at).toLocaleDateString()}</span></div><div className="flex items-center gap-3"><CalendarDays className="size-4 text-slate-400" /></div></div></section></aside></div></div></main>
    {selectvacanc && <EditVacancy  vacancy={selectvacanc} companies={companies} categories={categories} onClose={() =>setselectvacanc(null)} />}
    </>;
}
